# Generated by Django 4.0.6 on 2022-08-01 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=12)),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('transaction', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('dateandTime', models.DateTimeField()),
                ('dateSent', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=7)),
                ('last_name', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
                ('receipt_number', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('receipt_type', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.URLField()),
                ('dateandTime', models.DateTimeField()),
                ('source', models.URLField()),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
                ('bonus_credit', models.BooleanField()),
                ('transaction_reference', models.TextField()),
                ('transaction_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('balance', models.PositiveBigIntegerField()),
                ('transaction', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('pin', models.PositiveSmallIntegerField()),
                ('isActive', models.BooleanField()),
                ('currency', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('transaction_cost', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('discount', models.IntegerField()),
                ('points', models.SmallIntegerField()),
                ('tickets', models.CharField(max_length=8)),
                ('coupons', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('payment_due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('loan_term', models.IntegerField(null=True)),
                ('loan_balance', models.IntegerField(null=True)),
                ('dateissue', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.BigIntegerField(null=True)),
                ('Loan_purpose', models.CharField(max_length=100, null=True)),
                ('Interest_rate', models.IntegerField()),
                ('Wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=15)),
                ('cardholder_number', models.BigIntegerField()),
                ('expirydate', models.DateTimeField()),
                ('card_type', models.CharField(max_length=10)),
                ('dateIssued', models.DateField()),
                ('signature', models.CharField(max_length=5)),
                ('issuer', models.CharField(max_length=13)),
                ('CVVcode', models.CharField(max_length=8)),
                ('account', models.ManyToManyField(to='Wallet.customer')),
            ],
        ),
    ]
