# Generated by Django 4.0.6 on 2022-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_account_notification_receipt_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
