# Generated by Django 4.0.6 on 2022-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_alter_thirdparty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='first_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
