# Generated by Django 4.0.6 on 2022-08-22 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_remove_receipt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Interest_rate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_purpose',
            new_name='loan_purpose',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='dateSent',
            new_name='date_sent',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reward', to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='CVVcode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dateIssued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='signature',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='recipient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bonus_credit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dateandTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_reference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction',
            field=models.IntegerField(null=True),
        ),
    ]
